title: SDEbook 
logo: /docs/Thygesen2023-red.jpg
description: Suppl Info for SDE book
remote_theme: pages-themes/minimal 
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
